local options = {
  -- https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
  ensure_installed = {
    -- LSPs
    "lua-language-server", --lua_ls
    "bash-language-server", --bashls
    "docker-compose-language-service",
    "dockerfile-language-server",
    "hydra-lsp",
    "prettier",
    "rust-analyzer",
    "synk",
    "sonarlint-language-server",
    "trivy",
    "ast-grep",
    "jedi-language-server",
    "jdtls",
    "jq-lsp",
    "groovy-language-server",
    "haskell-language-server",
    "helm-ls",
    "json-lsp",
    "kotlin-language-server",
    "lemminx",
    "awk-language-server",
    "clangd",
    "cystalline",
    "deno",
    "eslint-ls",
    "gopls",
    "nginx-language-server",
    "powershell-editor-services",
    "puppet-editor-services",
    "ruby-lsp",
    "sqlls",
    "taplo",
    "terraform-ls",
    "tflint",
    "vim-language-server",
    "bash-debug-adapter",
    -- Linters
    "shellcheck",
    "hadolint",
    "action-lint",
    "ansible-lint",
    "alex",
    "biome",
    "cfn-lint",
    "cpplint",
    "detekt",
    "djlint",
    "flake8",
    "golanci-lint",
    "ast-grep",
    "jsonlint",
    "ktlint",
    "luacheck",
    "rubocop",
    "shellharden",
    "textlint",
    "tflint",
    "tfsec",
    "vint",
    "yamllint",
    -- Formatters
    "yamlfix",
    "yamlfmt",
    "xmlformatter",
    "tlint",
    "stylua",
    "sqlfmt",
    "shfmt",
    "rustywind",
    "prettierd",
    "ktlint",
    "jq",
    "google-java-format",
    "gci",
    "djlint",
    "clang-format",
    "ast-grep",
  }, -- not an option from mason.nvim

 -- PATH = "skip",

  ui = {
    icons = {
      package_pending = " ",
      package_installed = "󰄳 ",
      package_uninstalled = " 󰚌",
    },

    keymaps = {
      toggle_server_expand = "<CR>",
      install_server = "i",
      update_server = "u",
      check_server_version = "c",
      update_all_servers = "U",
      check_outdated_servers = "C",
      uninstall_server = "X",
      cancel_installation = "<C-c>",
    },
  },

  max_concurrent_installers = 10,
}

return options
